name: todo_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  get: 4.6.5

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
flutter_icons:
  ios: true
  android: true
  image_path: 'assets/images/logo.png'
flutter:
  uses-material-design: true
